server:
  port: ${GATEWAY_SERVER_PORT}

spring:
  application:
    name: gateway-service
  config:
    activate:
      on-profile: prod
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auths/**, /api/v1/users/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**
        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/v1/queues/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/ai/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true